# Generated by Django 4.0.3 on 2022-03-11 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Descripcion_impuestos_descuentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=2)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=8)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='Masculino', max_length=10)),
                ('numero_identidad', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nombre_producto', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
                ('fecha_elaboracion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_factura.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Factura_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura_factura_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_factura.factura')),
                ('productos_productos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_factura.producto')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='numeroIdentidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_factura.persona'),
        ),
    ]
