# Generated by Django 4.0.3 on 2022-03-11 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_factura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descripcion_impuesto_descuentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=3)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Descuentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_impuesto_descuentos_impuesto_descuento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_factura.descripcion_impuesto_descuentos')),
            ],
        ),
        migrations.CreateModel(
            name='factura_por_descuentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuentos_descuentos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_factura.descuentos')),
                ('factura_factura_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_factura.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion_impuesto_descuentos_impuesto_descuentos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_factura.descripcion_impuesto_descuentos')),
            ],
        ),
        migrations.CreateModel(
            name='Impuesto_por_factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura_factura_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_factura.factura')),
                ('impuesto_impuesto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_factura.impuesto')),
            ],
        ),
        migrations.DeleteModel(
            name='Descripcion_impuestos_descuentos',
        ),
        migrations.AddField(
            model_name='factura_detalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
