# Generated by Django 4.0.3 on 2022-03-12 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_factura', '0002_descripcion_impuesto_descuentos_descuentos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoria',
            new_name='categoria_categoria_id',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='precio_venta',
        ),
    ]
