# Generated by Django 4.0.3 on 2022-03-12 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_factura', '0003_rename_categoria_producto_categoria_categoria_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria_categoria_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_factura.categoria'),
        ),
    ]
