# Generated by Django 4.0.3 on 2022-03-12 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_factura', '0004_alter_producto_categoria_categoria_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoria_categoria_id',
            new_name='categoria_categoria_id_id',
        ),
    ]
