# Generated by Django 4.0.3 on 2022-03-12 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_factura', '0005_rename_categoria_categoria_id_producto_categoria_categoria_id_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoria_categoria_id_id',
            new_name='categoria_categoria_id',
        ),
    ]
