# Generated by Django 4.0.3 on 2022-03-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_factura', '0006_rename_categoria_categoria_id_id_producto_categoria_categoria_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.IntegerField(choices=[(1, 'Pastilla'), (2, 'Inyenccion'), (3, 'Jarabe'), (4, 'Analgésicos'), (5, 'Uso diario')]),
        ),
    ]
