# Generated by Django 4.0.3 on 2022-03-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_factura', '0011_rename_categoria_categoria_producto_categoria_categoria_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_elaboracion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
