# Generated by Django 4.0.3 on 2022-03-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_factura', '0012_alter_producto_fecha_elaboracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_elaboracion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(),
        ),
    ]
