# Generated by Django 4.0.3 on 2022-03-10 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiFactura', '0002_persona_genero_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apiFactura.persona'),
        ),
    ]
