# Generated by Django 4.0.3 on 2022-03-10 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiFactura', '0003_alter_cliente_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiFactura.persona')),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
