# Generated by Django 4.0.3 on 2022-03-10 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiFactura', '0004_factura_delete_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='persona',
            new_name='numeroIdentidad',
        ),
    ]
