# Generated by Django 4.0.3 on 2022-03-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiFactura', '0006_categoria_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AddField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='Masculino', max_length=10),
        ),
    ]
