# Generated by Django 4.0.3 on 2022-03-10 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiFactura', '0007_delete_producto_factura_total_alter_persona_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nombre_producto', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiFactura.categoria')),
            ],
        ),
    ]
